CREATE TABLE channels
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(15)                              NOT NULL,
    enabled       BOOLEAN DEFAULT TRUE                     NOT NULL,
    creation_time TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_time  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_table1 PRIMARY KEY (id)
);

CREATE TABLE delivery_log
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_schedule  BIGINT                                  NOT NULL,
    no_try       SMALLINT DEFAULT 1                      NOT NULL,
    created_time TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    log_message  VARCHAR(140),
    status       VARCHAR(15),
    CONSTRAINT pk_delivery_log PRIMARY KEY (id, id_schedule)
);

CREATE TABLE delivery_schedule
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_message   BIGINT                                  NOT NULL,
    id_channel   INTEGER                                 NOT NULL,
    created_time TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT pk_delivery_schedule_log PRIMARY KEY (id)
);

CREATE TABLE message_log
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message      VARCHAR(140)                            NOT NULL,
    created_time TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    user_author  VARCHAR(30)                             NOT NULL,
    CONSTRAINT pk_message_log PRIMARY KEY (id)
);

CREATE TABLE subscriptions
(
    id_user       BIGINT  NOT NULL,
    id_channel    INTEGER NOT NULL,
    enabled       BOOLEAN,
    creation_time TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_time  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_subscriptions PRIMARY KEY (id_user, id_channel)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(50)                             NOT NULL,
    email         VARCHAR(50)                             NOT NULL,
    phone         VARCHAR(15)                             NOT NULL,
    enabled       BOOLEAN DEFAULT TRUE                    NOT NULL,
    creation_time TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_time  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE INDEX ixfk_delivery_log_delivery_schedule ON delivery_log (id_schedule);

CREATE INDEX ixfk_delivery_schedule_channels ON delivery_schedule (id_message);

CREATE INDEX ixfk_subscriptions_channels ON subscriptions (id_channel);

CREATE INDEX ixfk_subscriptions_users ON subscriptions (id_user);

ALTER TABLE delivery_log
    ADD CONSTRAINT fk_delivery_log_delivery_schedule FOREIGN KEY (id_schedule) REFERENCES delivery_schedule (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE delivery_schedule
    ADD CONSTRAINT fk_delivery_schedule_channels FOREIGN KEY (id_message) REFERENCES channels (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE delivery_schedule
    ADD CONSTRAINT fk_delivery_schedule_message_log FOREIGN KEY (id_message) REFERENCES message_log (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE subscriptions
    ADD CONSTRAINT fk_subscriptions_channels FOREIGN KEY (id_channel) REFERENCES channels (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE subscriptions
    ADD CONSTRAINT fk_subscriptions_users FOREIGN KEY (id_user) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;